### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by I-am-PixelPioneer** [Yaziwel/Restore-RWKV#16]
作者您好，非常感谢您出色的工作。我在运行Restore_RWKV.py 时报错，已安装ninja1.11.1.3，以下是报错，貌似最下面一行说GPU架构不支持？

/home/hd/miniconda3/envs/pytorch/bin/python /home/hd/Restore-RWKV-main/model/Restore_RWKV.py 
Using /home/hd/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/hu/.cache/torch_extensions/py38_cu121/wkv/build.ninja...
/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module wkv...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Traceback (most recent call last):
  File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
    subprocess.run(
  File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hd/Restore-RWKV-main/model/Restore_RWKV.py", line 18, in <module>
    wkv_cuda = load(name="wkv", sources=["cuda/wkv_op.cpp", "cuda/wkv_cuda.cu"],
  File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1312, in load
    return _jit_compile(
  File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv'
[1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o 
FAILED: wkv_cuda.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_89'
ninja: build stopped: subcommand failed.

**Comment by Yaziwel** [comment]
> 作者您好，非常感谢您出色的工作。我在运行Restore_RWKV.py 时报错，已安装ninja1.11.1.3，以下是报错，貌似最下面一行说GPU架构不支持？
> 
> /home/hd/miniconda3/envs/pytorch/bin/python /home/hd/Restore-RWKV-main/model/Restore_RWKV.py Using /home/hd/.cache/torch_extensions/py38_cu121 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file /home/hu/.cache/torch_extensions/py38_cu121/wkv/build.ninja... /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST']. warnings.warn( Building extension module wkv... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) Traceback (most recent call last): File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build subprocess.run( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/hd/Restore-RWKV-main/model/Restore_RWKV.py", line 18, in wkv_cuda = load(name="wkv", sources=["cuda/wkv_op.cpp", "cuda/wkv_cuda.cu"], File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1312, in load return _jit_compile( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile _write_ninja_file_and_build_library( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library _run_ninja_build( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'wkv' [1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o FAILED: wkv_cuda.cuda.o /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o nvcc fatal : Unsupported gpu architecture 'compute_89' ninja: build stopped: subcommand failed.

试一下 pip install ninja --upgrade

**Comment by Yaziwel** [comment]
> 作者您好，非常感谢您出色的工作。我在运行Restore_RWKV.py 时报错，已安装ninja1.11.1.3，以下是报错，貌似最下面一行说GPU架构不支持？
> 
> /home/hd/miniconda3/envs/pytorch/bin/python /home/hd/Restore-RWKV-main/model/Restore_RWKV.py Using /home/hd/.cache/torch_extensions/py38_cu121 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file /home/hu/.cache/torch_extensions/py38_cu121/wkv/build.ninja... /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST']. warnings.warn( Building extension module wkv... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) Traceback (most recent call last): File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build subprocess.run( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/hd/Restore-RWKV-main/model/Restore_RWKV.py", line 18, in wkv_cuda = load(name="wkv", sources=["cuda/wkv_op.cpp", "cuda/wkv_cuda.cu"], File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1312, in load return _jit_compile( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile _write_ninja_file_and_build_library( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library _run_ninja_build( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'wkv' [1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o FAILED: wkv_cuda.cuda.o /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o nvcc fatal : Unsupported gpu architecture 'compute_89' ninja: build stopped: subcommand failed.

或者参考一下这个[issue](https://github.com/Yaziwel/Restore-RWKV/issues/4)

**Comment by I-am-PixelPioneer** [comment]
都试过了，我和[](https://github.com/Yaziwel/Restore-RWKV/issues/4)报错不太一样，他的方法我试了下还是不行

**Comment by I-am-PixelPioneer** [comment]
> > 作者您好，非常感谢您出色的工作。我在运行Restore_RWKV.py 时报错，已安装ninja1.11.1.3，以下是报错，貌似最下面一行说GPU架构不支持？
> > /home/hd/miniconda3/envs/pytorch/bin/python /home/hd/Restore-RWKV-main/model/Restore_RWKV.py Using /home/hd/.cache/torch_extensions/py38_cu121 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file /home/hu/.cache/torch_extensions/py38_cu121/wkv/build.ninja... /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST']. warnings.warn( Building extension module wkv... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) Traceback (most recent call last): File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build subprocess.run( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "/home/hd/Restore-RWKV-main/model/Restore_RWKV.py", line 18, in wkv_cuda = load(name="wkv", sources=["cuda/wkv_op.cpp", "cuda/wkv_cuda.cu"], File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1312, in load return _jit_compile( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile _write_ninja_file_and_build_library( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library _run_ninja_build( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'wkv' [1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o FAILED: wkv_cuda.cuda.o /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o nvcc fatal : Unsupported gpu architecture 'compute_89' ninja: build stopped: subcommand failed.
> 
> 或者参考一下这个[issue](https://github.com/Yaziwel/Restore-RWKV/issues/4)

都试过了，还是同样的报错。。。

**Comment by Yaziwel** [comment]
> > > 作者您好，非常感谢您出色的工作。我在运行Restore_RWKV.py 时报错，已安装ninja1.11.1.3，以下是报错，貌似最下面一行说GPU架构不支持？
> > > /home/hd/miniconda3/envs/pytorch/bin/python /home/hd/Restore-RWKV-main/model/Restore_RWKV.py Using /home/hd/.cache/torch_extensions/py38_cu121 as PyTorch extensions root... Detected CUDA files, patching ldflags Emitting ninja build file /home/hu/.cache/torch_extensions/py38_cu121/wkv/build.ninja... /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST']. warnings.warn( Building extension module wkv... Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N) Traceback (most recent call last): File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build subprocess.run( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/subprocess.py", line 516, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> > > The above exception was the direct cause of the following exception:
> > > Traceback (most recent call last): File "/home/hd/Restore-RWKV-main/model/Restore_RWKV.py", line 18, in wkv_cuda = load(name="wkv", sources=["cuda/wkv_op.cpp", "cuda/wkv_cuda.cu"], File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1312, in load return _jit_compile( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1722, in _jit_compile _write_ninja_file_and_build_library( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1834, in _write_ninja_file_and_build_library _run_ninja_build( File "/home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build raise RuntimeError(message) from e RuntimeError: Error building extension 'wkv' [1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o FAILED: wkv_cuda.cuda.o /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output wkv_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=wkv -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/TH -isystem /home/hd/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/hd/miniconda3/envs/pytorch/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -res-usage --maxrregcount 60 --use_fast_math -O3 -Xptxas -O3 -DTmax=262144 -std=c++17 -c /home/hd/Restore-RWKV-main/model/cuda/wkv_cuda.cu -o wkv_cuda.cuda.o nvcc fatal : Unsupported gpu architecture 'compute_89' ninja: build stopped: subcommand failed.
> > 
> > 
> > 或者参考一下这个[issue](https://github.com/Yaziwel/Restore-RWKV/issues/4)
> 
> 都试过了，还是同样的报错。。。

你加RWKV的QQ群问群里的人？他们有技术支持
